### ISSUE TITLE
GitHub Projectの使い方のキャッチアップ&使い方をWikiに書く

### ISSUE THREAD

**Issue by yuriemori** [code-polaris/reading-circle-tdd#4]

**Comment by yuriemori** [comment]
- 月ごとに３章ぐらい進めて月1で集まるスタイルなのでIteraionは月単位で設定
- そのIterationで進める予定のTDDの各章のタスクを作ってissueにconvertする
- 各章で詰まったりわからなくなったりしたらその章でコミュニケーションする
- 月1集まったタイミングで次の月のIterationと次の月にやる章のIssueを作成する

**Comment by shino51** [comment]
@yuriemori 
書きましたのでレビューお願いします
https://github.com/code-polaris/reading-circle-tdd/wiki/Project%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9
